companies:
  - name: Stripe
    execs:
      - Patrick Collison
      - John Collison
    themes:
      - payments
      - enterprise expansion
      - strategic partnerships
    aliases:
      - Stripe Inc.
    sector: Fintech
